# Generated by Django 2.2.28 on 2026-01-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20260125_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='page',
            old_name='Category',
            new_name='category',
        ),
    ]
